Catch all errors when creating an instance of an applet class. Also print the error msg instead of 'Applet failed'. I.e. http://www.virtualexp.net/WJump5.htm a NoClassDefFoundError is thrown that wasn't catched if java 3d isn't installed.
svn path=/trunk/kdelibs/; revision=266688