Use copy of value2string from khtml in ecmatest
    This fixes the build on windows where linking of ecmatest
    would fail because of an undefined reference to KJS::UString::qstring