Fixed compilation with alsa (parameter name was removed, re-added it conditionnally). Now I get link errors like alsaout.lo(.text+0x24c): undefined reference to `snd_strerror'. Anyone ?
svn path=/trunk/kdelibs/; revision=45135