Merge all changes from kdelibs 4.1 branch in one bunch. -- Merged revisions 886418,886844,886953,887309,887726,888820,888880,889247,889470,889593,889717,889786,890033,890048,890050-890051,890057,890178,890181,890187,890189,890299,890315,890350,890379-890380,890652,891650,891821,892738,893178,893660,894005,894202,894303,894493,894522,895086,895175,895704,895710,895748,895893,895896,896002,897682,897692,897715,897853,898678,899215,899545,901028,901165,901179,901205,901693,901922,902978,904385,904442,904803,906020,906060,906293,906463,906602,906618,908613,909712,911264 via svnmerge from svn+ssh://tmcguire@svn.kde.org/home/kde//branches/KDE/4.1/kdelibs
........
  r886418 | scripty | 2008-11-19 09:23:31 +0100 (Wed, 19 Nov 2008) | 1 line
  
  SVN_SILENT made messages (.desktop file)
........
  r886844 | wstephens | 2008-11-20 11:04:35 +0100 (Thu, 20 Nov 2008) | 3 lines
  
  Backport r880489 to 4.1 
  CCBUG:150772
........
  r886953 | rdieter | 2008-11-20 19:09:13 +0100 (Thu, 20 Nov 2008) | 4 lines
  
  backport unmess Utilities menu
  
  BUG: 161117
........
  r887309 | sengels | 2008-11-21 16:12:40 +0100 (Fri, 21 Nov 2008) | 2 lines
  
  backport r887303
  (fix knewstuff download)
........
  r887726 | orlovich | 2008-11-22 18:06:43 +0100 (Sat, 22 Nov 2008) | 2 lines
  
  Backport button grouping fix.
........
  r888820 | dfaure | 2008-11-25 13:33:21 +0100 (Tue, 25 Nov 2008) | 2 lines
  
  don't include passwords in url drags
........
  r888880 | dfaure | 2008-11-25 14:01:39 +0100 (Tue, 25 Nov 2008) | 2 lines
  
  Fix "xine-2 not found" error, we should check for the initialServiceName, not for xine-2. As reported by Andr?\195?\169 W?\195?\182bbeking.
........
  r889247 | dfaure | 2008-11-26 14:17:47 +0100 (Wed, 26 Nov 2008) | 2 lines
  
  Backport fix for patterns with two stars like *.ts.0*
........
  r889470 | sengels | 2008-11-26 22:58:54 +0100 (Wed, 26 Nov 2008) | 2 lines
  
  backport r889454
  default to Qt::NoBrush as a frame can be filled.
........
  r889593 | dfaure | 2008-11-27 10:33:45 +0100 (Thu, 27 Nov 2008) | 3 lines
  
  Fix item not disappearing when renaming it to ".foo" (hidden file)
  BUG: 164974
........
  r889717 | dfaure | 2008-11-27 13:45:55 +0100 (Thu, 27 Nov 2008) | 2 lines
  
  Backport: Fix infinite recursion and crash when the slot connected to newItems calls openUrl, like ktorrent's scanfolder plugin does. BUG #174920
........
  r889786 | dfaure | 2008-11-27 17:17:41 +0100 (Thu, 27 Nov 2008) | 4 lines
  
  Backport 889749+889785: fix for crash 135395 (closed long ago by mistake),
  by hiding the lineedit when M_NORENAME is set. Testcase: resuming aborted download.
  CCBUG: 135395
........
  r890033 | dfaure | 2008-11-28 12:21:14 +0100 (Fri, 28 Nov 2008) | 2 lines
  
  Backport user-feedback improvement (busy cursor during e.g. "toggle hidden files")
........
  r890048 | dfaure | 2008-11-28 13:23:30 +0100 (Fri, 28 Nov 2008) | 2 lines
  
  Backport r867820 by segato: change KDirListerCache::DirectoryData to KDirListerCacheDirectoryData to fix friend class error on older version of gcc
........
  r890050 | dfaure | 2008-11-28 13:27:59 +0100 (Fri, 28 Nov 2008) | 2 lines
  
  Backport 871340 & 872225 (updates to remote mimetypes), mostly so that further fixes can be backported too.
........
  r890051 | dfaure | 2008-11-28 13:31:03 +0100 (Fri, 28 Nov 2008) | 2 lines
  
  backport r866765 | habacker | msvc compile fix
........
  r890057 | dfaure | 2008-11-28 13:40:31 +0100 (Fri, 28 Nov 2008) | 3 lines
  
  Backport fixes for toggling hidden files (#174788), (and const iterators) from trunk.
  Now trunk and branch have the same code, except for the expandToUrl redesign/fix.
........
  r890178 | dfaure | 2008-11-28 15:16:08 +0100 (Fri, 28 Nov 2008) | 2 lines
  
  add kWarning to detect the problem of "deleted item not found in model" more easily.
........
  r890181 | dfaure | 2008-11-28 15:19:34 +0100 (Fri, 28 Nov 2008) | 2 lines
  
  konsole's copy/paste is broken, pastes many trailing spaces
........
  r890187 | dfaure | 2008-11-28 15:24:53 +0100 (Fri, 28 Nov 2008) | 2 lines
  
  Backport 890184: url-mimedata fix for #175910
........
  r890189 | dfaure | 2008-11-28 15:38:07 +0100 (Fri, 28 Nov 2008) | 2 lines
  
  backport: even kde3support code uses the kde4 kioslaves.
........
  r890299 | orlovich | 2008-11-28 21:24:57 +0100 (Fri, 28 Nov 2008) | 4 lines
  
  Merged revision 890298:
  Ergh, I suck. I broke textarea unsubmitted notification when fixing <input> one.
  
  BUG:176359
........
  r890315 | neundorf | 2008-11-28 22:59:38 +0100 (Fri, 28 Nov 2008) | 5 lines
  
  -change order of search directories, patch by Tejas Dinkar <tejas AT gja DOT in>
  
  Alex
........
  r890350 | dfaure | 2008-11-29 00:58:36 +0100 (Sat, 29 Nov 2008) | 2 lines
  
  repair source compat for kdebindings
........
  r890379 | dfaure | 2008-11-29 02:49:58 +0100 (Sat, 29 Nov 2008) | 4 lines
  
  Backport r890378:
  Don't reload the current directory when selecting a file in the file dialog
   (and especially not when that file is auto-selected because the previously current file got deleted externally - #173454 crash)
........
  r890380 | dfaure | 2008-11-29 02:52:01 +0100 (Sat, 29 Nov 2008) | 2 lines
  
  this line wasn't unused in the 4.x branch, re-add it
........
  r890652 | orlovich | 2008-11-29 19:53:13 +0100 (Sat, 29 Nov 2008) | 5 lines
  
  Merged revision 890651:
  When doing a fast-add of an option in a single-select, make sure we still 
  mark the first option as selected. Fixes NVidia driver searcher.
  
  BUG:176253
........
  r891650 | dfaure | 2008-12-02 15:35:59 +0100 (Tue, 02 Dec 2008) | 3 lines
  
  Fix crash when rowCount is called on a file, like when typing '*' in a treeview.
  BUG: 176555
........
  r891821 | whiting | 2008-12-02 23:50:02 +0100 (Tue, 02 Dec 2008) | 1 line
  
  backport ghost entries bugfix to 4.1 branch
........
  r892738 | scripty | 2008-12-05 08:37:18 +0100 (Fri, 05 Dec 2008) | 1 line
  
  SVN_SILENT made messages (.desktop file)
........
  r893178 | yurchor | 2008-12-06 09:23:52 +0100 (Sat, 06 Dec 2008) | 1 line
  
  Backport from trunk (removes header warnings)
........
  r893660 | scripty | 2008-12-07 08:50:46 +0100 (Sun, 07 Dec 2008) | 1 line
  
  SVN_SILENT made messages (.desktop file)
........
  r894005 | woebbe | 2008-12-07 18:07:22 +0100 (Sun, 07 Dec 2008) | 3 lines
  
  initialize richTextEnabled
  
  not sure whether true is the correct default but better than random
........
  r894202 | scripty | 2008-12-08 08:39:23 +0100 (Mon, 08 Dec 2008) | 1 line
  
  SVN_SILENT made messages (.desktop file)
........
  r894303 | ossi | 2008-12-08 13:41:49 +0100 (Mon, 08 Dec 2008) | 2 lines
  
  backport: make pty master non-blocking to avoid deadlocks
........
  r894493 | aacid | 2008-12-08 20:08:25 +0100 (Mon, 08 Dec 2008) | 4 lines
  
  backport r894491
  Save the value before priv->m_slider->setRange otherwise this with the connect changes the value of the spinbox and we lose it
  Fixes bug 177199
........
  r894522 | woebbe | 2008-12-08 21:22:03 +0100 (Mon, 08 Dec 2008) | 1 line
  
  use false as default for richTextEnabled as in trunk
........
  r895086 | sebsauer | 2008-12-10 00:49:59 +0100 (Wed, 10 Dec 2008) | 3 lines
  
  backport r895080
  Fix crash/assert if the name was empty.
........
  r895175 | scripty | 2008-12-10 09:19:14 +0100 (Wed, 10 Dec 2008) | 1 line
  
  SVN_SILENT made messages (.desktop file)
........
  r895704 | lueck | 2008-12-11 14:50:12 +0100 (Thu, 11 Dec 2008) | 3 lines
  
  backport of  entity move for partitionmanager docs in extragear sysadmin
  translators, please update your lang/user.entities in 4.1 if you want to use &partman; in doc translation
  CCMAIL:kde-i18n-doc@kde.org
........
  r895710 | yurchor | 2008-12-11 15:00:30 +0100 (Thu, 11 Dec 2008) | 1 line
  
  Backport
........
  r895748 | ogoffart | 2008-12-11 17:33:16 +0100 (Thu, 11 Dec 2008) | 4 lines
  
  Backport 895747  (Crashes in Qt application using phonon)
........
  r895893 | ereslibre | 2008-12-11 23:35:38 +0100 (Thu, 11 Dec 2008) | 6 lines
  
  Sorry ! forgot to backport this one to 4.1. This corresponds to commit 889449 in trunk. Backport fix of a fix =)
  
  CCMAIL: woebbeking@kde.org
  CCMAIL: wstephenson@kde.org
  CCMAIL: mcguire@kde.org
........
  r895896 | woebbe | 2008-12-11 23:40:30 +0100 (Thu, 11 Dec 2008) | 3 lines
  
  make the completion actions always checkable and DISABLE the disabled ones otherwise
  the user can still activate them and it looks really strange that some actions in one
  group are checkable/exclusive and some are not (e.g. address edits in KMail's composer).
........
  r896002 | porten | 2008-12-12 09:44:02 +0100 (Fri, 12 Dec 2008) | 7 lines
  
  Merged revision 896001:
  Ony way to fix TAB getting stuck on option elements. Another
  would be to reimplement handleEvent() and catch things there.
  
  Fixes
  BUG: 156164
  and 7 duplicates.
........
  r897682 | ehamberg | 2008-12-16 16:40:42 +0100 (Tue, 16 Dec 2008) | 5 lines
  
  Fix crash when leaving block select mode
  
  BUG: 177905
........
  r897692 | ehamberg | 2008-12-16 17:32:48 +0100 (Tue, 16 Dec 2008) | 3 lines
  
  don't move the cursor if cursor wrapping is off
........
  r897715 | dhaumann | 2008-12-16 18:41:26 +0100 (Tue, 16 Dec 2008) | 7 lines
  
  backport SVN commit 897704 by dhaumann:
  
  fixes
   - when [ ] Wrap Cursor is off, make it possible to move the cursor to the right again
   - when switching from no-wrap-cursor to wrap-cursor, ensure the cursor column is valid
     (reuse this function for block selection mode)
........
  r897853 | ehamberg | 2008-12-17 00:56:12 +0100 (Wed, 17 Dec 2008) | 3 lines
  
  ensureCursorColumnValid should check if the cursor is *in*valid...
........
  r898678 | dfaure | 2008-12-18 18:33:45 +0100 (Thu, 18 Dec 2008) | 2 lines
  
  Fix buttons not having the right label (yes/no/cancel instead of store/never for this site/do not store)
........
  r899215 | ilic | 2008-12-20 11:32:44 +0100 (Sat, 20 Dec 2008) | 1 line
  
  Preserve system value of LANGUAGE for the outside world. (bport: 899214)
........
  r899545 | scripty | 2008-12-21 08:52:12 +0100 (Sun, 21 Dec 2008) | 1 line
  
  SVN_SILENT made messages (.desktop file)
........
  r901028 | uwolfer | 2008-12-24 13:39:36 +0100 (Wed, 24 Dec 2008) | 5 lines
  
  Backport:
  SVN commit 901025 by uwolfer:
  
  Fix close button behavior for progress dialogs with busy indicators.
  CCBUG:178648
........
  r901165 | winterz | 2008-12-24 15:34:19 +0100 (Wed, 24 Dec 2008) | 10 lines
  
  backport SVN commit 901154 by winterz:
  
  In simpleBackupFile(), remove the backup file before copying the source file.
  This makes the copy work, just in case a backup file already exists.
  
  The remove will fail if a backup file doesn't exist (on the first call),
  but that's ok.
  
  Patch from Robby Stephenson.
........
  r901179 | berendsen | 2008-12-24 16:33:42 +0100 (Wed, 24 Dec 2008) | 1 line
  
  update lilypond syntax to 2.12: bookpart, and 2 context types are deprecated
........
  r901205 | dfaure | 2008-12-24 17:51:16 +0100 (Wed, 24 Dec 2008) | 2 lines
  
  Backport a bunch of commits in order to fix bugs 164584 and 178560
........
  r901693 | dfaure | 2008-12-26 13:55:56 +0100 (Fri, 26 Dec 2008) | 3 lines
  
  Backport fix for user-created desktop files not being useable on some distros (r901685)  --> the fix will be in KDE-4.1.4.
  CCBUG: 178561
........
  r901922 | grossard | 2008-12-26 23:25:46 +0100 (Fri, 26 Dec 2008) | 2 lines
  
  added a translator entity
........
  r902978 | grossard | 2008-12-29 16:50:29 +0100 (Mon, 29 Dec 2008) | 2 lines
  
  added a translator entity
........
  r904385 | scripty | 2009-01-02 08:47:54 +0100 (Fri, 02 Jan 2009) | 1 line
  
  SVN_SILENT made messages (.desktop file)
........
  r904442 | woebbe | 2009-01-02 12:11:55 +0100 (Fri, 02 Jan 2009) | 1 line
  
  createStandardContextMenu(): only add the "Default" completion entry if it's not disabled.
........
  r904803 | scripty | 2009-01-03 09:15:37 +0100 (Sat, 03 Jan 2009) | 1 line
  
  SVN_SILENT made messages (.desktop file)
........
  r906020 | dfaure | 2009-01-05 13:53:42 +0100 (Mon, 05 Jan 2009) | 2 lines
  
  Backport r906013, fix KArchiveDirectory::entry("./file").
........
  r906060 | dfaure | 2009-01-05 14:18:01 +0100 (Mon, 05 Jan 2009) | 3 lines
  
  Backport SVN commit 906059:
  Fix short/ushort error which broke prettyUrl for e.g. chinese unicode characters.
........
  r906293 | dfaure | 2009-01-05 22:39:03 +0100 (Mon, 05 Jan 2009) | 3 lines
  
  Fix wrong if() so that cervisia part can be loaded in konqueror.
  CCBUG: 178603
........
  r906463 | mueller | 2009-01-06 12:42:50 +0100 (Tue, 06 Jan 2009) | 2 lines
  
  KDE 4.1.4 preparations
........
  r906602 | dfaure | 2009-01-06 13:56:45 +0100 (Tue, 06 Jan 2009) | 6 lines
  
  "Fix" for enable-final by disabling it here.
  nepomuk/core/ontology/entitymanager.h:27: error: redefinition of ‘uint qHash(const QUrl&)’
  nepomuk/core/ontology/entity.cpp:35: error: ‘uint qHash(const QUrl&)’ previously defined here
  and:
  error: no matching function for call to ‘qHash(const Nepomuk::Tag&)’
........
  r906618 | dfaure | 2009-01-06 14:15:51 +0100 (Tue, 06 Jan 2009) | 2 lines
  
  Forgot to commit: the backport that makes extragear/base/konq-plugins/webarchiver compile with kde-4.1-branch.
........
  r908613 | franklin | 2009-01-10 01:33:38 +0100 (Sat, 10 Jan 2009) | 4 lines
  
  20090110 committed by Franklin
  
  fix doc untranslable problem
........
  r909712 | franklin | 2009-01-12 02:43:39 +0100 (Mon, 12 Jan 2009) | 1 line
  
  20090112 committed by Franklin
........
  r911264 | scripty | 2009-01-15 09:08:37 +0100 (Thu, 15 Jan 2009) | 1 line
  
  SVN_SILENT made messages (.desktop file)
........

svn path=/branches/kdepim/enterprise4/kdelibs-4.1-branch/; revision=911667