Revert previous commit. Breaks linking of applications using libkmdi (undefined reference to not_close_xpm). Use a workaround for IDEAl mode, so switching to TextOnly style of toolviews works without application restart.
svn path=/trunk/kdelibs/; revision=310981