Are SConscript supposed to be run on the command-line?
The file has a #! /usr/bin/env python
but running it causes:
Traceback (most recent call last):
  File "./SConscript", line 3, in ?
    Import('env')
NameError: name 'Import' is not defined

So I don't think these are executable nor should be marked with #!

CCMAIL:kde-buildsystem@kde.org

svn path=/trunk/KDE/kdelibs/; revision=471215