Fix linking of kdecore
Without this I get

CMakeFiles/KF5Codecs.dir/kcharsets.cpp.o: In function KCharsets::fromEntity(QString const&)': kcharsets.cpp:(.text+0x5cf): undefined reference tokde_findEntity'

Use gperf C++ generated code instead of C

See https://gcc.gnu.org/bugzilla/show_bug.cgi?id=41194 for more info

REVIEW: 128750