Fix --enable-final. Bug is somewhere else in our buildsystem but I can't fix that: without this patch I get the following error:
make[1]: Entering directory `/usr/src/KDE/kde-cvs-build/kdelibs/kdecore'
/bin/sh ../libtool --silent --mode=link gcc  -ansi -W -Wall -pedantic -Wchar-subscripts -Wshadow -Wpointer-arith -Wmissing-prototypes -Wwrite-strings -D_XOPEN_SOURCE=500 -D_BSD_SOURCE -DNDEBUG -O2   -Wformat-security -Wmissing-format-attribute   -o kgrantpty -R /opt/kde-3/lib -R /opt/qt-3/lib -R /usr/X11R6/lib -L/usr/X11R6/lib -L/opt/qt-3/lib -L/opt/kde-3/lib  kgrantpty.o ./libkdefakes.la
kgrantpty.o(.text+0x1aa): In function `main':
: warning: revoke is not implemented and will always fail
./.libs/libkdefakes.so: undefined reference to `QMetaObjectCleanUp::setMetaObject(QMetaObject*&)'
./.libs/libkdefakes.so: undefined reference to `QObject::activate_signal(QConnectionList*, QUObject*)'
./.libs/libkdefakes.so: undefined reference to `QMetaObjectCleanUp::~QMetaObjectCleanUp [in-charge]()'
./.libs/libkdefakes.so: undefined reference to `QObject::qt_property(int, int, QVariant*)'
....

and that's because libkdefakes_la.all_cpp.cpp includes kautoconfig.moc.cpp!! Coolo? Someone?

svn path=/trunk/kdelibs/; revision=210225